version: 2
endpoint: https://manipur.dailykit.org/datahub
metadata_directory: metadata
admin_secret: f902db26-8b34-43d8-86db-1737c1369f51
actions:
   kind: synchronous
   handler_webhook_baseurl: http://localhost:3000
