version: 2
endpoint: https://cookityourself.dailykit.org/datahub
admin_secret: 0a76c7f7-3cc0-46dc-b38d-00b7971ecc9d
metadata_directory: metadata
actions:
   kind: synchronous
   handler_webhook_baseurl: http://localhost:3000
