version: 2
endpoint: https://test.dailykit.org/datahub
admin_secret: 60ea76ab-5ab6-4f09-ad44-efeb00f978ce
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
