INSERT INTO
      brands."storeSetting" (id, type, identifier) 
VALUES
   (1, 'brand', 'Brand Logo'), 
   (2, 'visual', 'Favicon'), 
   (3, 'visual', 'App Title'),
   (4, 'availability', 'Store Availability'), 
   (5, 'brand', 'Brand Name'), 
   (6, 'availability', 'Pickup Availability'), 
   (7, 'availability', 'Delivery Availability'),
   (8, 'visual', 'Primary Color'), 
   (9, 'brand', 'Contact'), 
   (10, 'availability', 'Location'), 
   (11, 'visual', 'Slides'), 
   (12, 'sales', 'Food Cost Percent'), 
   (13, 'email', 'Email Notification'),  
   (14, 'availability', 'Store Live'),
   (15, 'rewards', 'Wallet Availability'), 
   (16, 'rewards', 'Loyalty Points Availability'),  
   (17, 'rewards', 'Coupons Availability'),
   (18, 'rewards', 'Loyalty Points Usage'),
   (19, 'rewards', 'Referral Availability'),
   (20, 'brand', 'Nav Links'),
   (21, 'brand', 'Terms and Conditions'),
   (22, 'brand', 'Privacy Policy'),
   (23, 'brand', 'Refund Policy'),
   (24, 'app', 'Scripts'),
   (25, 'brand', 'Policy Availability'),
   (26, 'email', 'Order Delivered'),
   (27, 'email', 'Order Cancelled');
   
  INSERT INTO
         brands."brand_storeSetting" ("brandId", "storeSettingId", value) 
VALUES
   ( 1000, 1, '{"url":"https://dailykit-133-test.s3.amazonaws.com/images/1596121558382.png"}'), 
   ( 1000, 2, '{"url":"https://dailykit-133-test.s3.amazonaws.com/images/1594373838496.png"}'), 
   ( 1000, 3, '{"title":"Test Store"}'), 
   ( 1000, 4, '{"to":"23:59","from":"00:01","isOpen":true,"shutMessage":"Will Never Open Again"}'), 
   ( 1000, 5, '{"name":"DailyKIT Store 1"}'), 
   ( 1000, 6, '{"isAvailable":true}'), 
   ( 1000, 7, '{"isAvailable":true}'), 
   ( 1000, 8, '{"color":"#798402"}'), 
   ( 1000, 9, '{"email":"test@dailykit.org","phoneNo":"+13124215900"}'), 
   ( 1000, 10, '{"lat":"33.8040277","lng":"-118.1700129","city":"Signal Hill","line1":"1798 East Willow Street","line2":"Opp. Blue Bird Store","state":"California","country":"United States","zipcode":"90755"}'), 
   ( 1000, 11, '[{"url":"https://images.unsplash.com/photo-1496412705862-e0088f16f791?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},{"url":"https://dailykit-133-test.s3.amazonaws.com/images/13699-4-3.jpg"}]'), 
   ( 1000, 12, '{"lowerLimit":30,"upperLimit":50}'), 
   ( 1000, 13, '{"name":"Test","email":"no-reply@dailykit.org","template":{"data":{"id":"{{new.id}}"},"template":{"name":"order_new","type":"email","format":"html"}}}'), 
   ( 1000, 14, '{"isStoreLive":false,"isStripeConfigured":true}'),
   (1000, 15, '{ "isAvailable": true }'), 
   (1000, 16, '{ "isAvailable": true }'),  
   (1000, 17, '{ "isAvailable": true }'),
   (1000, 18, '{ "max": 5, "percentage": 50, "converstionRate": 0.5 }'),
   (1000, 19, '{ "isAvailable": false }'),
   (1000, 20, '{ "aboutUs": "https://dailykit.org" }'),
   (1000, 21, '{ "value": "Nothing set!" }'),
   (1000, 22, '{ "value": "Nothing set!" }'),
   (1000, 23, '{ "value": "Nothing set!" }'),
   (1000, 24, '{ "value": "" }'),
   (1000, 25, '{ "isRefundPolicyAvailable": true, "isPrivacyPolicyAvailable": true, "isTermsAndConditionsAvailable": true }'),
   (1000, 26, '{ "name": "Test", "email": "no-reply@dailykit.org", "template": { "data": { "id": "{{new.id}}" }, "template": { "name": "order_delivered", "type": "email", "format": "html" } } }'),
   (1000, 27, '{ "name": "Test", "email": "no-reply@dailykit.org", "template": { "data": { "id": "{{new.id}}" }, "template": { "name": "order_cancelled", "type": "email", "format": "html" } } }');
