INSERT INTO
         brands."brand_storeSetting" ("brandId", "storeSettingId", value) 
VALUES
   ( 1, 1, '{"url":"https://dailykit-133-test.s3.amazonaws.com/images/1596121558382.png"}'), 
   ( 1, 2, '{"url":"https://dailykit-133-test.s3.amazonaws.com/images/1594373838496.png"}'), 
   ( 1, 3, '{"title":"Test Store"}'), 
   ( 1, 4, '{"to":"23:59","from":"00:01","isOpen":true,"shutMessage":"Will Never Open Again"}'), 
   ( 1, 5, '{"name":"DailyKIT Store 1"}'), 
   ( 1, 6, '{"isAvailable":true}'), 
   ( 1, 7, '{"isAvailable":true}'), 
   ( 1, 8, '{"color":"#798402"}'), 
   ( 1, 9, '{"email":"test@dailykit.org","phoneNo":"+13124215900"}'), 
   ( 1, 10, '{"lat":"33.8040277","lng":"-118.1700129","city":"Signal Hill","line1":"1798 East Willow Street","line2":"Opp. Blue Bird Store","state":"California","country":"United States","zipcode":"90755"}'), 
   ( 1, 11, '[{"url":"https://images.unsplash.com/photo-1496412705862-e0088f16f791?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"},{"url":"https://dailykit-133-test.s3.amazonaws.com/images/13699-4-3.jpg"}]'), 
   ( 1, 12, '{"lowerLimit":30,"upperLimit":50}'), 
   ( 1, 13, '{"name":"Test","email":"no-reply@dailykit.org","template":{"data":{"id":"{{new.id}}"},"template":{"name":"order_new","type":"email","format":"html"}}}'), 
   ( 1, 14, '{"isStoreLive":false,"isStripeConfigured":true}'),
   (1, 15, '{ "isAvailable": true }'), 
   (1, 16, '{ "isAvailable": true }'),  
   (1, 17, '{ "isAvailable": true }'),
   (1, 18, '{ "max": 5, "percentage": 50, "converstionRate": 0.5 }'),
   (1, 19, '{ "isAvailable": false }'),
   (1, 20, '{ "aboutUs": "https://dailykit.org" }'),
   (1, 21, '{ "value": "Nothing set!" }'),
   (1, 22, '{ "value": "Nothing set!" }'),
   (1, 23, '{ "value": "Nothing set!" }'),
   (1, 24, '{ "value": "" }'),
   (1, 25, '{ "isRefundPolicyAvailable": true, "isPrivacyPolicyAvailable": true, "isTermsAndConditionsAvailable": true }'),
   (1, 26, '{ "name": "Test", "email": "no-reply@dailykit.org", "template": { "data": { "id": "{{new.id}}" }, "template": { "name": "order_delivered", "type": "email", "format": "html" } } }'),
   (1, 27, '{ "name": "Test", "email": "no-reply@dailykit.org", "template": { "data": { "id": "{{new.id}}" }, "template": { "name": "order_cancelled", "type": "email", "format": "html" } } }');
