INSERT INTO settings.app (id, title) VALUES 
(1, 'Order App')
,(2, 'Products App')
,(3, 'Inventory App')
,(4, 'Subscription App')
,(5, 'CRM App')
,(6, 'Settings App')
,(7, 'Safety App')
,(8, 'Menu App')
,(9, 'Brand App')
,(10, 'Insights App')
;

INSERT INTO settings."appPermission" ("appId",route,title,"fallbackMessage") VALUES 
-- Order App
 (1,'orders','ROUTE_READ','You do not have sufficient permission to see orders listing')
,(1,'planned','ROUTE_READ','You do not have sufficient permission to see planned mode.')
,(1,'order','ROUTE_READ','You do not have sufficient permission to see order details.')
,(1,'planned/ready-to-eat','ROUTE_READ','You do not have sufficient permission to see planned ready to eat details.')
,(1,'planned/inventory','ROUTE_READ','You do not have sufficient permission to see planned inventory details.')
,(1,'home','ROUTE_READ','You do not have sufficient permission to see order app.')
-- Recipe App
,(2,'home','ROUTE_READ','You do not have sufficient permission to see products app.')
,(2,'recipes','ROUTE_READ','You do not have sufficient permission to see recipes listing.')
,(2,'recipe','ROUTE_READ','You do not have sufficient permission to see recipe details.')
,(2,'ingredients','ROUTE_READ','You do not have sufficient permission to see ingredients listing.')
,(2,'ingredient','ROUTE_READ','You do not have sufficient permission to see ingredient details.')
,(2,'simple-recipe-product','ROUTE_READ','You do not have sufficient permission to see simple recipe product details.')
,(2,'customizable-product','ROUTE_READ','You do not have sufficient permission to see customizable product details.')
,(2,'combo-product','ROUTE_READ','You do not have sufficient permission to see combo product details.')
,(2,'products','ROUTE_READ','You do not have sufficient permission to see products listing.')
,(2,'inventory-product','ROUTE_READ','You do not have sufficient permission to see inventory product details.')
-- Inventory App
,(3,'suppliers','ROUTE_READ','You do not have sufficient permission to see suppliers listing.')
,(3,'supplier','ROUTE_READ','You do not have sufficient permission to see suppliers details.')
,(3,'home','ROUTE_READ','You do not have sufficient permission to see inventory app.')
,(3,'items','ROUTE_READ','You do not have sufficient permission to see items listing.')
,(3,'item','ROUTE_READ','You do not have sufficient permission to see item details.')
,(3,'work-orders','ROUTE_READ','You do not have sufficient permission to see work orders.')
,(3,'work-orders/sachet','ROUTE_READ','You do not have sufficient permission to see work order sachet.')
,(3,'work-orders/bulk','ROUTE_READ','You do not have sufficient permission to see work order bulk.')
,(3,'purchase-orders','ROUTE_READ','You do not have sufficient permission to see purchase orders.')
,(3,'purchase-orders/item','ROUTE_READ','You do not have sufficient permission to see purchase order item.')
,(3,'purchase-orders/packaging','ROUTE_READ','You do not have sufficient permission to see purchase order packaging.')
,(3,'packagings','ROUTE_READ','You do not have sufficient permission to see packagings.')
,(3,'packaging','ROUTE_READ','You do not have sufficient permission to see packagings details.')
,(3,'packaging-hub','ROUTE_READ','You do not have sufficient permission to see packaging hub.')
,(3,'packaging-hub/product','ROUTE_READ','You do not have sufficient permission to see packaging hub product.')
,(3,'packaging-hub/products','ROUTE_READ','You do not have sufficient permission to see packaging hub products.')
-- Subscription App
,(4,'home','ROUTE_READ','You do not have sufficient permission to see subscription app.')
,(4,'menu','ROUTE_READ','You do not have sufficient permission to see menu page.')
,(4,'subscriptions','ROUTE_READ','You do not have sufficient permission to see subscription listing.')
,(4,'subscription','ROUTE_READ','You do not have sufficient permission to see subscription details.')
-- CRM App
,(5,'home','ROUTE_READ','You do not have sufficient permission to see crm app.')
,(5,'customers','ROUTE_READ','You do not have sufficient permission to see customers listing.')
,(5,'referral-plans','ROUTE_READ','You do not have sufficient permission to see referral plans.')
,(5,'coupons','ROUTE_READ','You do not have sufficient permission to see coupons listing.')
,(5,'campaigns','ROUTE_READ','You do not have sufficient permission to see campaign listing.')
,(5,'campaign','ROUTE_READ','You do not have sufficient permission to see campaign details.')
,(5,'customer','ROUTE_READ','You do not have sufficient permission to see customer details.')
,(5,'coupon','ROUTE_READ','You do not have sufficient permission to see coupon details.')
-- Settings App
,(6,'home','ROUTE_READ','You do not have sufficient permission to see settings app.')
,(6,'apps','ROUTE_READ','You do not have sufficient permission to see apps listing.')
,(6,'users','ROUTE_READ','You do not have sufficient permission to see users listing.')
,(6,'user','ROUTE_READ','You do not have sufficient permission to see user details.')
,(6,'roles','ROUTE_READ','You do not have sufficient permission to see roles listing.')
,(6,'role','ROUTE_READ','You do not have sufficient permission to see role details.')
,(6,'devices','ROUTE_READ','You do not have sufficient permission to see devices listing.')
,(6,'stations','ROUTE_READ','You do not have sufficient permission to see stations listing.')
,(6,'station','ROUTE_READ','You do not have sufficient permission to see station details.')
,(6,'master-lists','ROUTE_READ','You do not have sufficient permission to see master listing.')
,(6,'master-list','ROUTE_READ','You do not have sufficient permission to see master list details.')
-- Safety App
,(7,'home','ROUTE_READ','You do not have sufficient permission to see safety app.')
,(7,'checks','ROUTE_READ','You do not have sufficient permission to see checks listing.')
,(7,'check','ROUTE_READ','You do not have sufficient permission to see check details.')
-- Online Store
,(8,'home','ROUTE_READ','You do not have sufficient permission to see store app.')
,(8,'collections','ROUTE_READ','You do not have sufficient permission to see collections listing.')
,(8,'collection','ROUTE_READ','You do not have sufficient permission to see collection details.')
,(8,'settings','ROUTE_READ','You do not have sufficient permission to see store settings.')
,(8,'recurrence','ROUTE_READ','You do not have sufficient permission to see recurrence details.')
-- Brand App
,(9,'home','ROUTE_READ','You do not have sufficient permission to see brand app.')
,(9,'brands','ROUTE_READ','You do not have sufficient permission to see brands listing')
,(9,'brand','ROUTE_READ','You do not have sufficient permission to see brand details.')
;
