INSERT INTO
      brands."storeSetting" (type, identifier) 
VALUES
   ('brand', 'Brand Logo'), 
   ('visual', 'Favicon'), 
   ('visual', 'App Title'),
   ('availability', 'Store Availability'), 
   ('brand', 'Brand Name'), 
   ('availability', 'Pickup Availability'), 
   ('availability', 'Delivery Availability'),
   ('visual', 'Primary Color'), 
   ('brand', 'Contact'), 
   ('availability', 'Location'), 
   ('visual', 'Slides'), 
   ('sales', 'Food Cost Percent'), 
   ('email', 'Email Notification'),  
   ('availability', 'Store Live'),
   ('rewards', 'Wallet Availability'), 
   ('rewards', 'Loyalty Points Availability'),  
   ('rewards', 'Coupons Availability'),
   ('rewards', 'Loyalty Points Usage'),
   ('rewards', 'Referral Availability'),
   ('brand', 'Nav Links'),
   ('brand', 'Terms and Conditions'),
   ('brand', 'Privacy Policy'),
   ('brand', 'Refund Policy'),
   ('app', 'Scripts'),
   ('brand', 'Policy Availability'),
   ('email', 'Order Delivered'),
   ('email', 'Order Cancelled');
